version: "3.7"
services:

  # Backend
  backend:
    build: .
    ports:
      - "8080:8080"
    networks:
      - vaultnet

  # Frontend
  frontend:
    build: ./deployments/docker/frontend
    ports:
      - "8081:80"
    networks:
      - vaultnet

networks:
  vaultnet:
