name: 2vault-Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build-test
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go 1.16
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # See: https://goreleaser.com/ci/actions/

      - name: Set version env
        run: echo 'APP_VERSION='$(git describe --tags --always) >> $GITHUB_ENV

      - name: Set build env
        run: echo 'APP_BUILD='$(date +%FT%T%z) >> $GITHUB_ENV

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Test with Coverage
        run: go test -v  -coverprofile='coverage.txt' -covermode=atomic ./...

      - name: Upload Codecov
        uses: codecov/codecov-action@v1.0.14
        if: success()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}